[package]
name = "sample-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
mongodb = { version = "2.0", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bson = "2.0"